FROM node:22-alpine

WORKDIR /app

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

# package.jsonをコピーして依存解決
COPY package*.json ./
RUN npm install

COPY . .

RUN chown -R appuser:appgroup /app
RUN chmod +x /app/scripts/entrypoint.sh

# 開発モード指定
ENV NODE_ENV=development

# 非rootユーザーに切り替え
USER appuser

# 開発サーバー起動（ts-node-dev前提）
ENTRYPOINT ["/app/scripts/entrypoint.sh"]
CMD ["npm", "run", "dev"]